.Dd March 18, 2020
.Dt HELLO_DARTRIX
.Sh NAME
.Nm clojure
.Nd clojure template from package:hello_dartrix
.Sh SYNOPSIS
Passed as an arg to dartrix:new -x package:hello_dartrix,
.Nm clojure
.Op Fl c Ar param
.Sh DESCRIPTION
.Pp
The
.Em clojure
parameters are:
.Bl -tag -width Ds
.It Ar param1
Description of param 1 ...
.Pp
Default: param1-default
.El
.Sh EXAMPLES
Example goes here...
.Sh SEE ALSO
.Xr hello
