.Dd March 18, 2020
.Dt HELLO_DARTRIX
.Sh NAME
.Nm dart
.Nd Hello World demo in Dart.
.Sh SYNOPSIS
.Nm dartrix:new hello -t dart [options]
.Sh DESCRIPTION
.Pp
The
.Em dart
parameters are:
.Bl -tag -width Ds
.It Ar param1
Description of param 1 ...
.Pp
Default: param1-default
.El
.Sh EXAMPLES
Example goes here...
