.Dd March 18, 2020
.Dt HELLO_DARTRIX
.Sh NAME
.Nm java
.Nd java template from package:hello_dartrix
.Sh SYNOPSIS
dartrix:new hello -t java [options]
.Sh DESCRIPTION
.Pp
The
.Em java
template options are:
.Bl -tag -width Ds
.It Ar param1
Description of param 1 ...
.Pp
Default: param1-default
.El
.Sh EXAMPLES
Example goes here...
